// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/signin": {
    params: {};
  };
  "/signup": {
    params: {};
  };
  "/auth/callback": {
    params: {};
  };
  "/favicon.ico": {
    params: {};
  };
  "/dashboard": {
    params: {};
  };
  "/dashboard/project": {
    params: {};
  };
  "/dashboard/ticket": {
    params: {};
  };
  "/dashboard/files": {
    params: {};
  };
  "/dashboard/milestones": {
    params: {};
  };
  "/dashboard/milestones/:id": {
    params: {
      "id": string;
    };
  };
  "/dashboard/tasks": {
    params: {};
  };
  "/dashboard/deployments": {
    params: {};
  };
  "/dashboard/billing": {
    params: {};
  };
  "/dashboard/activity": {
    params: {};
  };
  "/dashboard/settings": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/signin" | "/signup" | "/auth/callback" | "/favicon.ico" | "/dashboard" | "/dashboard/project" | "/dashboard/ticket" | "/dashboard/files" | "/dashboard/milestones" | "/dashboard/milestones/:id" | "/dashboard/tasks" | "/dashboard/deployments" | "/dashboard/billing" | "/dashboard/activity" | "/dashboard/settings";
  };
  "routes/index.tsx": {
    id: "routes/index";
    page: "/";
  };
  "routes/signin.tsx": {
    id: "routes/signin";
    page: "/signin";
  };
  "routes/signup.tsx": {
    id: "routes/signup";
    page: "/signup";
  };
  "routes/auth-callback.tsx": {
    id: "routes/auth-callback";
    page: "/auth/callback";
  };
  "routes/favicon.tsx": {
    id: "routes/favicon";
    page: "/favicon.ico";
  };
  "routes/dashboard.tsx": {
    id: "routes/dashboard";
    page: "/dashboard";
  };
  "routes/dashboard-project.tsx": {
    id: "routes/dashboard-project";
    page: "/dashboard/project";
  };
  "routes/dashboard-ticket.tsx": {
    id: "routes/dashboard-ticket";
    page: "/dashboard/ticket";
  };
  "routes/dashboard-files.tsx": {
    id: "routes/dashboard-files";
    page: "/dashboard/files";
  };
  "routes/dashboard-milestones.tsx": {
    id: "routes/dashboard-milestones";
    page: "/dashboard/milestones";
  };
  "routes/dashboard-milestone-detail.tsx": {
    id: "routes/dashboard-milestone-detail";
    page: "/dashboard/milestones/:id";
  };
  "routes/dashboard-tasks.tsx": {
    id: "routes/dashboard-tasks";
    page: "/dashboard/tasks";
  };
  "routes/dashboard-deployments.tsx": {
    id: "routes/dashboard-deployments";
    page: "/dashboard/deployments";
  };
  "routes/dashboard-billing.tsx": {
    id: "routes/dashboard-billing";
    page: "/dashboard/billing";
  };
  "routes/dashboard-activity.tsx": {
    id: "routes/dashboard-activity";
    page: "/dashboard/activity";
  };
  "routes/dashboard-settings.tsx": {
    id: "routes/dashboard-settings";
    page: "/dashboard/settings";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/index": typeof import("./app/routes/index.tsx");
  "routes/signin": typeof import("./app/routes/signin.tsx");
  "routes/signup": typeof import("./app/routes/signup.tsx");
  "routes/auth-callback": typeof import("./app/routes/auth-callback.tsx");
  "routes/favicon": typeof import("./app/routes/favicon.tsx");
  "routes/dashboard": typeof import("./app/routes/dashboard.tsx");
  "routes/dashboard-project": typeof import("./app/routes/dashboard-project.tsx");
  "routes/dashboard-ticket": typeof import("./app/routes/dashboard-ticket.tsx");
  "routes/dashboard-files": typeof import("./app/routes/dashboard-files.tsx");
  "routes/dashboard-milestones": typeof import("./app/routes/dashboard-milestones.tsx");
  "routes/dashboard-milestone-detail": typeof import("./app/routes/dashboard-milestone-detail.tsx");
  "routes/dashboard-tasks": typeof import("./app/routes/dashboard-tasks.tsx");
  "routes/dashboard-deployments": typeof import("./app/routes/dashboard-deployments.tsx");
  "routes/dashboard-billing": typeof import("./app/routes/dashboard-billing.tsx");
  "routes/dashboard-activity": typeof import("./app/routes/dashboard-activity.tsx");
  "routes/dashboard-settings": typeof import("./app/routes/dashboard-settings.tsx");
};